
package trackingandpayment;

import java.awt.geom.RoundRectangle2D;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;



public class FpsHomeSection extends javax.swing.JFrame {
        
    int positionX = 0, positionY = 0;
    
    public FpsHomeSection() {         
        setUndecorated(true); 
        initComponents();             
        setLocationRelativeTo(null);        
        setShape(new RoundRectangle2D. Double(0,0, getWidth(), getHeight(), 20, 20));
    }
    
    private String studName;
    private int studNum;
    public FpsHomeSection(int studNum, String studName){        
        this.studNum = studNum;
        this.studName = studName;
        getDueDates();
        setUndecorated(true);
        initComponents();             
        setLocationRelativeTo(null);        
        setShape(new RoundRectangle2D. Double(0,0, getWidth(), getHeight(), 20, 20));           
    }
    
    String reminder1;
    String reminder2;
    String reminder3;
    private void getDueDates(){
        Connection conn = null;
        
        try{
            // connect to database
            conn = FpsDBConnection.dbConnect();
            String query = "SELECT * FROM tbl_fee_list WHERE StudentNum = ? ORDER BY DueDate";
            PreparedStatement ps = conn.prepareStatement(query);
            ps.setInt(1, studNum);
            ResultSet rs = ps.executeQuery();
            
            // will get the first three reminders
            if (rs.next()) {
                String category = rs.getString(3);
                String amount = rs.getString(4);
                String date = rs.getString(5);
                
                reminder1 = String.format("<html>%s on %s<br>Amount: %s</html>", category, date, amount);                            }
            else{
                reminder1 = "No current fees.";
            }
            
            if(rs.next()){
                String category = rs.getString(3);
                String amount = rs.getString(4);
                String date = rs.getString(5);
                
                reminder2 = String.format("<html>%s on %s<br>Amount: %s</html>", category, date, amount);
            }
            
            if(rs.next()){
                String category = rs.getString(3);
                String amount = rs.getString(4);
                String date = rs.getString(5);
                
                reminder3 = String.format("<html>%s on %s<br>Amount: %s</html>", category, date, amount);
            }
        }       
        catch (SQLException e){
            JOptionPane.showMessageDialog(this, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        CVSU_LOGO = new javax.swing.JLabel();
        iconHome = new javax.swing.JRadioButton();
        iconViewFees = new javax.swing.JRadioButton();
        iconPay = new javax.swing.JRadioButton();
        iconReceipt = new javax.swing.JRadioButton();
        iconTranHistory = new javax.swing.JRadioButton();
        epay = new javax.swing.JLabel();
        exitbtn = new javax.swing.JButton();
        minibtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lbl_Greetings = new javax.swing.JLabel();
        jPanelGreetings = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanelViewFees = new javax.swing.JPanel();
        viewfees = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnViewFees = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        viewfees3 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnTranHis = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        btnPay = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        viewfees1 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        btnGenReceipt = new javax.swing.JButton();
        viewfees2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        epay3 = new javax.swing.JLabel();
        epay2 = new javax.swing.JLabel();
        pendingpayment = new javax.swing.JLabel();
        txtDue1 = new javax.swing.JLabel();
        txtDue2 = new javax.swing.JLabel();
        txtDue3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        CVSU_LOGO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/24.png"))); // NOI18N

        iconHome.setBackground(new java.awt.Color(255, 255, 255));
        iconHome.setToolTipText("Home");
        iconHome.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        iconHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/home.png"))); // NOI18N
        iconHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iconHomeActionPerformed(evt);
            }
        });

        iconViewFees.setBackground(new java.awt.Color(255, 255, 255));
        iconViewFees.setToolTipText("View Fees");
        iconViewFees.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        iconViewFees.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/ViewFees.png"))); // NOI18N
        iconViewFees.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iconViewFeesActionPerformed(evt);
            }
        });

        iconPay.setBackground(new java.awt.Color(255, 255, 255));
        iconPay.setToolTipText("Pay");
        iconPay.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        iconPay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/PayFees.png"))); // NOI18N
        iconPay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iconPayActionPerformed(evt);
            }
        });

        iconReceipt.setBackground(new java.awt.Color(255, 255, 255));
        iconReceipt.setToolTipText("Receipt");
        iconReceipt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        iconReceipt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconReceipt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/student (2).png"))); // NOI18N
        iconReceipt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iconReceiptActionPerformed(evt);
            }
        });

        iconTranHistory.setBackground(new java.awt.Color(255, 255, 255));
        iconTranHistory.setToolTipText("Transaction History");
        iconTranHistory.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        iconTranHistory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/TransactionHistory.png"))); // NOI18N
        iconTranHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iconTranHistoryActionPerformed(evt);
            }
        });

        epay.setBackground(new java.awt.Color(255, 255, 255));
        epay.setFont(new java.awt.Font("Timeline", 1, 24)); // NOI18N
        epay.setForeground(new java.awt.Color(30, 0, 110));
        epay.setText("Cash-VSU");

        exitbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/exit button.png"))); // NOI18N
        exitbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitbtnActionPerformed(evt);
            }
        });

        minibtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/minimize.png"))); // NOI18N
        minibtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minibtnActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(249, 249, 249));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(249, 249, 249), 50, true));
        jPanel2.setOpaque(false);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_Greetings.setBackground(new java.awt.Color(255, 255, 255));
        lbl_Greetings.setFont(new java.awt.Font("Source Code Pro", 1, 36)); // NOI18N
        lbl_Greetings.setForeground(new java.awt.Color(30, 0, 110));
        lbl_Greetings.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Greetings.setText("Hello " + studName + "!");
        jPanel2.add(lbl_Greetings, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 670, 70));

        jPanelGreetings.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanelGreetingsLayout = new javax.swing.GroupLayout(jPanelGreetings);
        jPanelGreetings.setLayout(jPanelGreetingsLayout);
        jPanelGreetingsLayout.setHorizontalGroup(
            jPanelGreetingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        jPanelGreetingsLayout.setVerticalGroup(
            jPanelGreetingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        jPanel2.add(jPanelGreetings, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 800, 80));

        jPanel4.setBackground(new java.awt.Color(249, 249, 249));
        jPanel4.setForeground(new java.awt.Color(186, 186, 186));
        jPanel4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelViewFees.setBackground(new java.awt.Color(255, 255, 255));
        jPanelViewFees.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 20, true));
        jPanelViewFees.setOpaque(false);
        jPanelViewFees.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        viewfees.setFont(new java.awt.Font("Front Page Neue", 0, 18)); // NOI18N
        viewfees.setForeground(new java.awt.Color(30, 0, 110));
        viewfees.setText("View Fees");
        jPanelViewFees.add(viewfees, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 90, 20));

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/view.png"))); // NOI18N

        jLabel8.setFont(new java.awt.Font("Segoe UI Semilight", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(186, 186, 186));
        jLabel8.setText("Look at your available fees.");

        btnViewFees.setBackground(new java.awt.Color(30, 0, 110));
        btnViewFees.setFont(new java.awt.Font("Front Page Neue", 0, 18)); // NOI18N
        btnViewFees.setForeground(new java.awt.Color(255, 255, 255));
        btnViewFees.setText("CLICK HERE");
        btnViewFees.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnViewFees.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewFeesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addGap(0, 163, Short.MAX_VALUE)
                .addComponent(btnViewFees))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, Short.MAX_VALUE)
                .addGap(22, 22, 22)
                .addComponent(btnViewFees))
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel8)
                .addContainerGap(69, Short.MAX_VALUE))
        );

        jPanelViewFees.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 300, -1));

        jPanel4.add(jPanelViewFees, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 330, 130));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 20, true));
        jPanel6.setOpaque(false);
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        viewfees3.setFont(new java.awt.Font("Front Page Neue", 0, 18)); // NOI18N
        viewfees3.setForeground(new java.awt.Color(30, 0, 110));
        viewfees3.setText("Transaction History");
        jPanel6.add(viewfees3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 200, 20));

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/transact history.png"))); // NOI18N

        jLabel6.setFont(new java.awt.Font("Segoe UI Semilight", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(186, 186, 186));
        jLabel6.setText("Check your transactions here."); // NOI18N

        btnTranHis.setBackground(new java.awt.Color(30, 0, 110));
        btnTranHis.setFont(new java.awt.Font("Front Page Neue", 0, 18)); // NOI18N
        btnTranHis.setForeground(new java.awt.Color(255, 255, 255));
        btnTranHis.setText("CLICK HERE");
        btnTranHis.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTranHis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTranHisActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnTranHis))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                        .addComponent(jLabel4)))
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTranHis, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jPanel6.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 300, -1));

        jPanel4.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 570, 330, 130));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 20, true));
        jPanel7.setOpaque(false);
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));

        btnPay.setBackground(new java.awt.Color(30, 0, 110));
        btnPay.setFont(new java.awt.Font("Front Page Neue", 0, 18)); // NOI18N
        btnPay.setForeground(new java.awt.Color(255, 255, 255));
        btnPay.setText("CLICK HERE");
        btnPay.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPayActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/pay.png"))); // NOI18N

        jLabel9.setFont(new java.awt.Font("Segoe UI Semilight", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(186, 186, 186));
        jLabel9.setText("To get you fully paid, go to our payment system");

        viewfees1.setFont(new java.awt.Font("Front Page Neue", 0, 18)); // NOI18N
        viewfees1.setForeground(new java.awt.Color(30, 0, 110));
        viewfees1.setText("Pay");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap(193, Short.MAX_VALUE)
                .addComponent(btnPay)
                .addGap(20, 20, 20))
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(viewfees1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel9)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(viewfees1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPay, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel7.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, -1));

        jPanel4.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 400, 350, 130));

        jPanel8.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 20, true));
        jPanel8.setOpaque(false);
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/User.png"))); // NOI18N
        jPanel8.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, 60, 50));

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));

        jLabel10.setFont(new java.awt.Font("Segoe UI Semilight", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(186, 186, 186));
        jLabel10.setText("Generate your receipt.");

        btnGenReceipt.setBackground(new java.awt.Color(30, 0, 110));
        btnGenReceipt.setFont(new java.awt.Font("Front Page Neue", 0, 18)); // NOI18N
        btnGenReceipt.setForeground(new java.awt.Color(255, 255, 255));
        btnGenReceipt.setText("CLICK HERE");
        btnGenReceipt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGenReceipt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenReceiptActionPerformed(evt);
            }
        });

        viewfees2.setFont(new java.awt.Font("Front Page Neue", 0, 18)); // NOI18N
        viewfees2.setForeground(new java.awt.Color(30, 0, 110));
        viewfees2.setText("Receipt");

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addContainerGap(197, Short.MAX_VALUE)
                .addComponent(btnGenReceipt)
                .addGap(16, 16, 16))
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(viewfees2, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel10)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addComponent(viewfees2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(btnGenReceipt, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        jPanel8.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 9, 350, 130));

        jPanel4.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 570, 350, 130));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setEnabled(false);
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/background image.png"))); // NOI18N
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel4.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        epay3.setBackground(new java.awt.Color(255, 255, 255));
        epay3.setFont(new java.awt.Font("Front Page Neue", 0, 18)); // NOI18N
        epay3.setForeground(new java.awt.Color(30, 0, 110));
        epay3.setText("MANAGE YOUR FEES");
        jPanel4.add(epay3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, -1, -1));

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 810, 700));

        epay2.setBackground(new java.awt.Color(255, 255, 255));
        epay2.setFont(new java.awt.Font("Front Page Neue", 0, 18)); // NOI18N
        epay2.setForeground(new java.awt.Color(30, 0, 110));
        epay2.setText("MANAGE YOUR FEES");
        jPanel2.add(epay2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, -1, -1));

        pendingpayment.setFont(new java.awt.Font("Timeline", 1, 14)); // NOI18N
        pendingpayment.setForeground(new java.awt.Color(30, 0, 110));
        pendingpayment.setText("REMINDERS");

        txtDue1.setFont(new java.awt.Font("Source Code Pro", 0, 12)); // NOI18N
        txtDue1.setForeground(new java.awt.Color(30, 0, 110));
        txtDue1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtDue1.setText(reminder1);

        txtDue2.setFont(new java.awt.Font("Source Code Pro", 0, 12)); // NOI18N
        txtDue2.setForeground(new java.awt.Color(30, 0, 110));
        txtDue2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtDue2.setText(reminder2);

        txtDue3.setFont(new java.awt.Font("Source Code Pro", 0, 12)); // NOI18N
        txtDue3.setForeground(new java.awt.Color(30, 0, 110));
        txtDue3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtDue3.setText(reminder3);

        jButton1.setBackground(new java.awt.Color(30, 0, 110));
        jButton1.setFont(new java.awt.Font("Front Page Neue", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("LOGOUT");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(iconHome, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(iconViewFees, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(iconReceipt, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(iconTranHistory, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(iconPay, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 773, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(pendingpayment, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                        .addGap(21, 21, 21))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDue3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtDue2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtDue1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(CVSU_LOGO)
                        .addGap(18, 18, 18)
                        .addComponent(epay)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(minibtn, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(exitbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(exitbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CVSU_LOGO)
                            .addComponent(minibtn, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(epay, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 740, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(108, 108, 108)
                                .addComponent(pendingpayment)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDue1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDue2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDue3, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(91, 91, 91)
                                .addComponent(iconHome, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(iconViewFees, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(iconPay, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(15, 15, 15)
                                .addComponent(iconReceipt, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(iconTranHistory, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void iconHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iconHomeActionPerformed
        // do nothing
    }//GEN-LAST:event_iconHomeActionPerformed

    private void iconViewFeesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iconViewFeesActionPerformed
        new FpsViewFees(studNum, studName).setVisible(true);
        dispose();
    }//GEN-LAST:event_iconViewFeesActionPerformed

    private void iconPayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iconPayActionPerformed
        new FpsPayment(studNum, studName).setVisible(true);
        dispose ();
    }//GEN-LAST:event_iconPayActionPerformed

    private void iconReceiptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iconReceiptActionPerformed
        new FpsGenReceipt(studNum, studName).setVisible(true);
        dispose();
    }//GEN-LAST:event_iconReceiptActionPerformed

    private void iconTranHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iconTranHistoryActionPerformed
        new FpsTransactionHistory(studNum, studName).setVisible(true);
        dispose();
    }//GEN-LAST:event_iconTranHistoryActionPerformed

    private void exitbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitbtnActionPerformed
        this.dispose();
    }//GEN-LAST:event_exitbtnActionPerformed

    private void minibtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minibtnActionPerformed
        this.setExtendedState(FpsHomeSection.ICONIFIED);
    }//GEN-LAST:event_minibtnActionPerformed

    private void btnViewFeesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewFeesActionPerformed
        new FpsViewFees(studNum, studName).setVisible(true);
        dispose();
    }//GEN-LAST:event_btnViewFeesActionPerformed

    private void btnTranHisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTranHisActionPerformed
        new FpsTransactionHistory(studNum, studName).setVisible(true);
        dispose();
    }//GEN-LAST:event_btnTranHisActionPerformed

    private void btnPayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPayActionPerformed
        new FpsPayment(studNum, studName).setVisible(true);
        dispose ();
    }//GEN-LAST:event_btnPayActionPerformed

    private void btnGenReceiptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenReceiptActionPerformed
        new FpsGenReceipt(studNum, studName).setVisible(true);
        dispose();
    }//GEN-LAST:event_btnGenReceiptActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        FpsLogin lg = new FpsLogin();
        lg.frame.setVisible(true);
        lg.frame.setLocationRelativeTo(this);
        dispose();

    }//GEN-LAST:event_jButton1ActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FpsHomeSection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FpsHomeSection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FpsHomeSection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FpsHomeSection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FpsHomeSection().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CVSU_LOGO;
    private javax.swing.JButton btnGenReceipt;
    private javax.swing.JButton btnPay;
    private javax.swing.JButton btnTranHis;
    private javax.swing.JButton btnViewFees;
    private javax.swing.JLabel epay;
    private javax.swing.JLabel epay2;
    private javax.swing.JLabel epay3;
    private javax.swing.JButton exitbtn;
    private javax.swing.JRadioButton iconHome;
    private javax.swing.JRadioButton iconPay;
    private javax.swing.JRadioButton iconReceipt;
    private javax.swing.JRadioButton iconTranHistory;
    private javax.swing.JRadioButton iconViewFees;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel jPanelGreetings;
    private javax.swing.JPanel jPanelViewFees;
    private javax.swing.JLabel lbl_Greetings;
    private javax.swing.JButton minibtn;
    private javax.swing.JLabel pendingpayment;
    private javax.swing.JLabel txtDue1;
    private javax.swing.JLabel txtDue2;
    private javax.swing.JLabel txtDue3;
    private javax.swing.JLabel viewfees;
    private javax.swing.JLabel viewfees1;
    private javax.swing.JLabel viewfees2;
    private javax.swing.JLabel viewfees3;
    // End of variables declaration//GEN-END:variables
}

