
package trackingandpayment;

import java.awt.geom.RoundRectangle2D;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;




public class FpsTransactionHistory extends javax.swing.JFrame {
    

    int positionX = 0, positionY = 0;
    
    public FpsTransactionHistory() {  
        setUndecorated(true);        
        initComponents();        
        setLocationRelativeTo(null);        
        setShape(new RoundRectangle2D. Double(0,0, getWidth(), getHeight(), 20, 20));
    }
    
    private String studName;
    private int studNum;
    public FpsTransactionHistory(int studNum, String studName) {    
        this.studNum = studNum;
        this.studName = studName;        
        setUndecorated(true);        
        initComponents();        
        setLocationRelativeTo(null);        
        setShape(new RoundRectangle2D. Double(0,0, getWidth(), getHeight(), 20, 20));
        
        getTranHistory();
    }
    
    private void getTranHistory(){
        Connection conn = null;
        try {
            // connect to database
            conn = FpsDBConnection.dbConnect();
            String query = "SELECT FeeCode AS 'Fee Code', StudentNum AS 'Student No.', Category, Amount, DueDate AS 'Due Date', DatePaid AS 'Date Paid' FROM transaction_history WHERE StudentNum = ?";
            PreparedStatement ps = conn.prepareStatement(query);
            ps.setInt(1, studNum);
            ResultSet rs = ps.executeQuery();
            tblTransactions.setModel(DbUtils.resultSetToTableModel(rs));
        }
        catch(SQLException ex) {
            JOptionPane.showMessageDialog(this,  ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        CVSU_LOGO = new javax.swing.JLabel();
        HomeButton = new javax.swing.JRadioButton();
        iconViewFees = new javax.swing.JRadioButton();
        iconPay = new javax.swing.JRadioButton();
        iconReceipt = new javax.swing.JRadioButton();
        iconTranHistory = new javax.swing.JRadioButton();
        epay = new javax.swing.JLabel();
        exitbtn = new javax.swing.JButton();
        minibtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        tblTranHistory = new javax.swing.JScrollPane();
        tblTransactions = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        CVSU_LOGO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/24.png"))); // NOI18N

        HomeButton.setBackground(new java.awt.Color(255, 255, 255));
        HomeButton.setToolTipText("Home");
        HomeButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        HomeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/home.png"))); // NOI18N
        HomeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeButtonActionPerformed(evt);
            }
        });

        iconViewFees.setBackground(new java.awt.Color(255, 255, 255));
        iconViewFees.setToolTipText("View Fees");
        iconViewFees.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        iconViewFees.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/ViewFees.png"))); // NOI18N
        iconViewFees.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iconViewFeesActionPerformed(evt);
            }
        });

        iconPay.setBackground(new java.awt.Color(255, 255, 255));
        iconPay.setToolTipText("Pay");
        iconPay.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        iconPay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/PayFees.png"))); // NOI18N
        iconPay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iconPayActionPerformed(evt);
            }
        });

        iconReceipt.setBackground(new java.awt.Color(255, 255, 255));
        iconReceipt.setToolTipText("Receipt");
        iconReceipt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        iconReceipt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconReceipt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/student (2).png"))); // NOI18N
        iconReceipt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iconReceiptActionPerformed(evt);
            }
        });

        iconTranHistory.setBackground(new java.awt.Color(255, 255, 255));
        iconTranHistory.setToolTipText("Transaction History");
        iconTranHistory.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        iconTranHistory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/TransactionHistory.png"))); // NOI18N
        iconTranHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iconTranHistoryActionPerformed(evt);
            }
        });

        epay.setBackground(new java.awt.Color(255, 255, 255));
        epay.setFont(new java.awt.Font("Timeline", 1, 24)); // NOI18N
        epay.setForeground(new java.awt.Color(30, 0, 110));
        epay.setText("Cash-VSU");

        exitbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/exit button.png"))); // NOI18N
        exitbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitbtnActionPerformed(evt);
            }
        });

        minibtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/minimize.png"))); // NOI18N
        minibtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minibtnActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(249, 249, 249));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(249, 249, 249), 50, true));
        jPanel2.setEnabled(false);
        jPanel2.setOpaque(false);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setEnabled(false);
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 61, -1, -1));

        jPanel4.setBackground(new java.awt.Color(249, 249, 249));
        jPanel4.setForeground(new java.awt.Color(186, 186, 186));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Front Page Neue", 0, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(30, 0, 110));
        jLabel5.setText("TRANSACTION HISTORY");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, -1, -1));

        tblTransactions.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblTranHistory.setViewportView(tblTransactions);

        jPanel4.add(tblTranHistory, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 900, 550));

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 940, 720));

        jButton4.setBackground(new java.awt.Color(30, 0, 110));
        jButton4.setFont(new java.awt.Font("Front Page Neue", 1, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("LOGOUT");
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(CVSU_LOGO)
                        .addGap(18, 18, 18)
                        .addComponent(epay)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(minibtn, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(exitbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(HomeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(iconViewFees, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(iconReceipt, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(iconTranHistory, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(iconPay, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1000, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(exitbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CVSU_LOGO)
                            .addComponent(minibtn, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(epay)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(HomeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(iconViewFees, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(iconPay, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(iconReceipt, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(iconTranHistory, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 740, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62)))
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HomeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeButtonActionPerformed
        new FpsHomeSection(studNum, studName).setVisible(true);
        dispose();
    }//GEN-LAST:event_HomeButtonActionPerformed

    private void iconViewFeesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iconViewFeesActionPerformed
        new FpsViewFees(studNum, studName).setVisible(true);
        dispose();
    }//GEN-LAST:event_iconViewFeesActionPerformed

    private void iconPayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iconPayActionPerformed
        new FpsPayment(studNum, studName).setVisible(true);
        dispose ();
    }//GEN-LAST:event_iconPayActionPerformed

    private void iconReceiptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iconReceiptActionPerformed
        new FpsGenReceipt(studNum, studName).setVisible(true);
        dispose();
    }//GEN-LAST:event_iconReceiptActionPerformed

    private void iconTranHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iconTranHistoryActionPerformed
        // do nothing
    }//GEN-LAST:event_iconTranHistoryActionPerformed

    private void exitbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitbtnActionPerformed
        dispose();
    }//GEN-LAST:event_exitbtnActionPerformed

    private void minibtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minibtnActionPerformed
        this.setExtendedState(FpsTransactionHistory.ICONIFIED);
    }//GEN-LAST:event_minibtnActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        FpsLogin lg = new FpsLogin();
        lg.frame.setVisible(true);
        lg.frame.setLocationRelativeTo(this);
        dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FpsTransactionHistory().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CVSU_LOGO;
    private javax.swing.JRadioButton HomeButton;
    private javax.swing.JLabel epay;
    private javax.swing.JButton exitbtn;
    private javax.swing.JRadioButton iconPay;
    private javax.swing.JRadioButton iconReceipt;
    private javax.swing.JRadioButton iconTranHistory;
    private javax.swing.JRadioButton iconViewFees;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JButton minibtn;
    private javax.swing.JScrollPane tblTranHistory;
    private javax.swing.JTable tblTransactions;
    // End of variables declaration//GEN-END:variables
}

