
package trackingandpayment;

import java.awt.geom.RoundRectangle2D;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;


public class FpsViewFees extends javax.swing.JFrame {
    

    int positionX = 0, positionY = 0;
    
    public FpsViewFees() {       
        setUndecorated(true);        
        initComponents();               
        setLocationRelativeTo(null);       
        setShape(new RoundRectangle2D. Double(0,0, getWidth(), getHeight(), 20, 20));
    }
    private String studName;
    private int studNum;
    public FpsViewFees(int studNum, String studName) { 
        this.studNum = studNum;
        this.studName = studName;
        setUndecorated(true);        
        initComponents();               
        setLocationRelativeTo(null);       
        setShape(new RoundRectangle2D. Double(0,0, getWidth(), getHeight(), 20, 20));
        grabData();
    }
    
    private void grabData(){
        Connection conn = null;
        try {
            // connect to database
            conn = FpsDBConnection.dbConnect();
            String query = "SELECT FeeCode AS 'Fee Code', StudentNum AS 'Student No.', Category, Amount, DueDate AS 'Due Date' FROM tbl_fee_list WHERE StudentNum = ?";
            PreparedStatement ps = conn.prepareStatement(query);
            ps.setInt(1, studNum);
            ResultSet rs = ps.executeQuery();
            tblViewFees.setModel(DbUtils.resultSetToTableModel(rs));
        }
        catch(SQLException ex) {
            JOptionPane.showMessageDialog(this,  ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        CVSU_LOGO = new javax.swing.JLabel();
        iconHome = new javax.swing.JRadioButton();
        iconViewFees = new javax.swing.JRadioButton();
        iconPay = new javax.swing.JRadioButton();
        iconReceipt = new javax.swing.JRadioButton();
        iconTranHistory = new javax.swing.JRadioButton();
        epay = new javax.swing.JLabel();
        exitbtn = new javax.swing.JButton();
        minibtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblViewFees = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        CVSU_LOGO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/24.png"))); // NOI18N

        iconHome.setBackground(new java.awt.Color(255, 255, 255));
        iconHome.setToolTipText("Home");
        iconHome.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        iconHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/home.png"))); // NOI18N
        iconHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iconHomeActionPerformed(evt);
            }
        });

        iconViewFees.setBackground(new java.awt.Color(255, 255, 255));
        iconViewFees.setToolTipText("View Fees");
        iconViewFees.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        iconViewFees.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/ViewFees.png"))); // NOI18N
        iconViewFees.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iconViewFeesActionPerformed(evt);
            }
        });

        iconPay.setBackground(new java.awt.Color(255, 255, 255));
        iconPay.setToolTipText("Pay");
        iconPay.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        iconPay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/PayFees.png"))); // NOI18N
        iconPay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iconPayActionPerformed(evt);
            }
        });

        iconReceipt.setBackground(new java.awt.Color(255, 255, 255));
        iconReceipt.setToolTipText("Receipt");
        iconReceipt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        iconReceipt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconReceipt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/student (2).png"))); // NOI18N
        iconReceipt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iconReceiptActionPerformed(evt);
            }
        });

        iconTranHistory.setBackground(new java.awt.Color(255, 255, 255));
        iconTranHistory.setToolTipText("Transaction History");
        iconTranHistory.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        iconTranHistory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/TransactionHistory.png"))); // NOI18N
        iconTranHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iconTranHistoryActionPerformed(evt);
            }
        });

        epay.setBackground(new java.awt.Color(255, 255, 255));
        epay.setFont(new java.awt.Font("Timeline", 1, 24)); // NOI18N
        epay.setForeground(new java.awt.Color(30, 0, 110));
        epay.setText("Cash-VSU");

        exitbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/exit button.png"))); // NOI18N
        exitbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitbtnActionPerformed(evt);
            }
        });

        minibtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/minimize.png"))); // NOI18N
        minibtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minibtnActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(249, 249, 249));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(249, 249, 249), 50, true));
        jPanel2.setEnabled(false);
        jPanel2.setOpaque(false);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setEnabled(false);
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 61, -1, -1));

        jPanel4.setBackground(new java.awt.Color(249, 249, 249));
        jPanel4.setForeground(new java.awt.Color(186, 186, 186));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Front Page Neue", 0, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(30, 0, 110));
        jLabel5.setText("VIEW FEES");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 30, -1, -1));

        tblViewFees.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblViewFees);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 900, 590));

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 930, 720));

        jButton1.setBackground(new java.awt.Color(30, 0, 110));
        jButton1.setFont(new java.awt.Font("Front Page Neue", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("LOGOUT");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(iconHome, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(iconViewFees, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(iconReceipt, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(iconTranHistory, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(iconPay, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 972, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 3, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(CVSU_LOGO)
                        .addGap(18, 18, 18)
                        .addComponent(epay)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(minibtn, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(exitbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(exitbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CVSU_LOGO)
                            .addComponent(minibtn, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(epay)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(iconHome, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(iconViewFees, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(iconPay, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(iconReceipt, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(iconTranHistory, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 740, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61)))
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void iconHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iconHomeActionPerformed
        new FpsHomeSection(studNum, studName).setVisible(true);
        dispose();
    }//GEN-LAST:event_iconHomeActionPerformed

    private void iconViewFeesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iconViewFeesActionPerformed
        // do nothing
    }//GEN-LAST:event_iconViewFeesActionPerformed

    private void iconPayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iconPayActionPerformed
        new FpsPayment(studNum, studName).setVisible(true);
        dispose ();
    }//GEN-LAST:event_iconPayActionPerformed

    private void iconReceiptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iconReceiptActionPerformed
        new FpsGenReceipt(studNum, studName).setVisible(true);
        dispose();
    }//GEN-LAST:event_iconReceiptActionPerformed

    private void iconTranHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iconTranHistoryActionPerformed
        new FpsTransactionHistory(studNum, studName).setVisible(true);
        dispose();
    }//GEN-LAST:event_iconTranHistoryActionPerformed

    private void exitbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitbtnActionPerformed
        this.dispose();
    }//GEN-LAST:event_exitbtnActionPerformed

    private void minibtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minibtnActionPerformed
        this.setExtendedState(FpsViewFees.ICONIFIED);
    }//GEN-LAST:event_minibtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        FpsLogin lg = new FpsLogin();
        lg.frame.setVisible(true);
        lg.frame.setLocationRelativeTo(this);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FpsViewFees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FpsViewFees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FpsViewFees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FpsViewFees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FpsViewFees().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CVSU_LOGO;
    private javax.swing.JLabel epay;
    private javax.swing.JButton exitbtn;
    private javax.swing.JRadioButton iconHome;
    private javax.swing.JRadioButton iconPay;
    private javax.swing.JRadioButton iconReceipt;
    private javax.swing.JRadioButton iconTranHistory;
    private javax.swing.JRadioButton iconViewFees;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton minibtn;
    protected javax.swing.JTable tblViewFees;
    // End of variables declaration//GEN-END:variables
}

