
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package atm_machine;

import java.awt.Color;
import java.sql.*;

import javax.swing.JOptionPane;


@SuppressWarnings("serial")
public class SignUp extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public SignUp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lblMyBank = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        txtFName = new javax.swing.JTextField();
        passfPin = new javax.swing.JPasswordField();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        lblSignUp = new javax.swing.JLabel();
        btnSubmit = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtLName = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        txtEmail = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        txtAccID = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        btnGoToLogin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));
        jPanel4.setForeground(new java.awt.Color(255, 255, 255));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon("img/icons8-bank-cards-100.png")); // NOI18N

        lblMyBank.setFont(new java.awt.Font("Bahnschrift", 1, 48)); // NOI18N
        lblMyBank.setForeground(new java.awt.Color(255, 255, 255));
        lblMyBank.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMyBank.setText("MYBANK");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMyBank)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(lblMyBank, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        txtFName.setFont(new java.awt.Font("Bahnschrift", 0, 16)); // NOI18N
        txtFName.setForeground(new java.awt.Color(102, 102, 102));
        txtFName.setText("First Name");
        txtFName.setToolTipText("");
        txtFName.setBorder(null);
        txtFName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtFNameFocusGained(evt);
            }
        	public void focusLost(java.awt.event.FocusEvent evt) {
        		txtFNameFocusLost(evt);
        	}
        });
        txtFName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FirstNActionPerformed(evt);
            }
        });

        passfPin.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        passfPin.setForeground(new java.awt.Color(102, 102, 102));
        passfPin.setText("1234");
        passfPin.setBorder(null);
        passfPin.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passfPINFocusGained(evt);
            }

        	public void focusLost(java.awt.event.FocusEvent evt) {
        		passfPinFocusLost(evt);
        	}
        });
        passfPin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PINActionPerformed(evt);
            }
        });

        jSeparator2.setBackground(new java.awt.Color(101, 101, 101));
        jSeparator2.setForeground(new java.awt.Color(51, 51, 51));

        jSeparator3.setBackground(new java.awt.Color(101, 101, 101));
        jSeparator3.setForeground(new java.awt.Color(51, 51, 51));

        lblSignUp.setFont(new java.awt.Font("Bahnschrift", 1, 60)); // NOI18N
        lblSignUp.setText("Sign Up");

        btnSubmit.setBackground(new java.awt.Color(255, 255, 255));
        btnSubmit.setFont(new java.awt.Font("Bahnschrift", 0, 24)); // NOI18N
        btnSubmit.setText("Submit");
        btnSubmit.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        btnSubmit.addMouseListener(new java.awt.event.MouseAdapter() {          
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton1MouseExited(evt);
            }
        });
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel4.setText("X");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        txtLName.setFont(new java.awt.Font("Bahnschrift", 0, 16)); // NOI18N
        txtLName.setForeground(new java.awt.Color(102, 102, 102));
        txtLName.setText("Last Name");
        txtLName.setToolTipText("");
        txtLName.setBorder(null);
        txtLName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtLNameFocusGained(evt);
            }
        	public void focusLost(java.awt.event.FocusEvent evt) {
        		txtLNameFocusLost(evt);
        	}
        });
        txtLName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LastNActionPerformed(evt);
            }
        });

        jSeparator4.setBackground(new java.awt.Color(101, 101, 101));
        jSeparator4.setForeground(new java.awt.Color(51, 51, 51));

        txtEmail.setFont(new java.awt.Font("Bahnschrift", 0, 16)); // NOI18N
        txtEmail.setForeground(new java.awt.Color(102, 102, 102));
        txtEmail.setText("Email");
        txtEmail.setToolTipText("");
        txtEmail.setBorder(null);
        txtEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtEmailFocusGained(evt);
            }
            
        	public void focusLost(java.awt.event.FocusEvent evt) {
        		txtEmailFocusLost(evt);
        	}
        });
        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgeActionPerformed(evt);
            }
        });

        jSeparator5.setBackground(new java.awt.Color(101, 101, 101));
        jSeparator5.setForeground(new java.awt.Color(51, 51, 51));

        txtAccID.setFont(new java.awt.Font("Bahnschrift", 0, 16)); // NOI18N
        txtAccID.setForeground(new java.awt.Color(102, 102, 102));
        txtAccID.setText("Account ID");
        txtAccID.setToolTipText("");
        txtAccID.setBorder(null);
        txtAccID.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtAccIDFocusGained(evt);
            }

        	public void focusLost(java.awt.event.FocusEvent evt) {
        		txtAccIDFocusLost(evt);
        	}
        });
        txtAccID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AccIDActionPerformed(evt);
            }
        });

        jSeparator6.setBackground(new java.awt.Color(101, 101, 101));
        jSeparator6.setForeground(new java.awt.Color(51, 51, 51));

        btnGoToLogin.setBackground(new java.awt.Color(255, 255, 255));
        btnGoToLogin.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        btnGoToLogin.setText("Already Have an Account?");
        btnGoToLogin.setToolTipText("");
        btnGoToLogin.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        btnGoToLogin.setContentAreaFilled(false);
        btnGoToLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnGoToLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton2MouseExited(evt);
            }
        });
        btnGoToLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoToLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(141, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(lblSignUp)
                        .addGap(126, 126, 126)
                        .addComponent(jLabel4)
                        .addGap(19, 19, 19))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(199, 199, 199))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(btnGoToLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(98, 98, 98))))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtFName, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtEmail, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jSeparator5)
                        .addComponent(passfPin, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtLName, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                    .addComponent(jSeparator4)
                    .addComponent(txtAccID)
                    .addComponent(jSeparator6))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel4))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(lblSignUp, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(50, 50, 50)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFName, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLName, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jSeparator4, javax.swing.GroupLayout.DEFAULT_SIZE, 8, Short.MAX_VALUE)
                    .addComponent(jSeparator2))
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtAccID, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(passfPin, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(78, 78, 78)))
                .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(btnGoToLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>
    
 // checks if PIN is an int and only 4 digits
  	boolean isValid (String pin) {
  		try {
  			// converts str to int if it fails
  			// catch will execute
  			Integer.parseInt(pin);
  			if (pin.length() == 4) {
  				return true;
  			}
  			else {
  				JOptionPane.showMessageDialog(this, "Invalid PIN. Only 4-Digit is allowed.");
  				return false;
  			}
  		}
  		catch (NumberFormatException e) {
  			JOptionPane.showMessageDialog(this, "Invalid PIN. Only numbers are allowed");
  			return false;
  		}
  	}

  	private void Clear() {
  		txtFName.setText("First Name");
  		txtLName.setText("Last Name");
  		txtEmail.setText("Email");
  		txtAccID.setText("Account ID");
  		passfPin.setText("1234");
  	}
  	
//Submit Button
    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {                                         
    	String pin = String.valueOf(passfPin.getPassword());
    	
    	if(txtFName.getText().isEmpty() || txtLName.getText().isEmpty() || txtEmail.getText().isEmpty() || txtAccID.getText().isEmpty() || pin.isEmpty()) {
    		JOptionPane.showMessageDialog(this, "Missing Information");
    	}
    	else {
    		if (isValid(pin)) {
    			Connection conn= null;
        		try {
        			conn = DBConnection.dbConnect();
        			// mysql insert statement
        			String query = "INSERT INTO usertbl (FirstName, LastName, Email, AccountID, Pin, Balance) VALUES (?,?,?,?,?,?)";
        			// issues the mysql query
        			PreparedStatement Add = conn.prepareStatement(query);
        			Add.setString(1, txtFName.getText());
        			Add.setString(2, txtLName.getText());
        			Add.setString(3, txtEmail.getText());
        			Add.setString(4, txtAccID.getText());
        			Add.setInt(5, Integer.valueOf(pin));
        			Add.setInt(6, 0);
        			
        			// executes the PreparedStatement
        			Add.execute();
        			JOptionPane.showMessageDialog(this, "Succesful account creation.");
        			Clear();
        			conn.close();
        		}
        		catch(SQLException e ) {
        			// error code for duplicate entry
        			if (e.getErrorCode() == 1062) {
        				JOptionPane.showMessageDialog(this, "Account already exists. Try again.");
            			Clear();
        			}
        			else {
        				JOptionPane.showMessageDialog(this, e);
        			}
        		}
    		}
    	}
    }                   
    
//Go to Login
    private void btnGoToLoginActionPerformed(java.awt.event.ActionEvent evt) {                                         
    	this.dispose();
    	new Login().setVisible(true);
    }                                        

    private void txtFNameFocusGained(java.awt.event.FocusEvent evt) {                                   
    	if(txtFName.getText().equals("First Name")) {
    		txtFName.setText("");
    	}
    }         
    
    private void txtFNameFocusLost(java.awt.event.FocusEvent evt) {                                
    	if (txtFName.getText().trim().equals("") || txtFName.getText().trim().toLowerCase().equals("First Name")) {
    		txtFName.setText("First Name");
    	}
    }
    
    private void txtLNameFocusGained(java.awt.event.FocusEvent evt) {                                  
    	if(txtLName.getText().equals("Last Name")) {
    		txtLName.setText("");
    	}
    } 
    
    private void txtLNameFocusLost(java.awt.event.FocusEvent evt) {                                
    	if (txtLName.getText().trim().equals("") || txtLName.getText().trim().toLowerCase().equals("Last Name")) {
    		txtLName.setText("Last Name");
    	}
    }
    
    private void txtEmailFocusGained(java.awt.event.FocusEvent evt) {                                
    	if(txtEmail.getText().equals("Email")) {
    		txtEmail.setText("");
    	}
    }
    
    private void txtEmailFocusLost(java.awt.event.FocusEvent evt) {                                
    	if (txtEmail.getText().trim().equals("") || txtEmail.getText().trim().toLowerCase().equals("Email")) {
    		txtEmail.setText("Email");
    	}
    }
    
    private void txtAccIDFocusGained(java.awt.event.FocusEvent evt) {                                  
    	if(txtAccID.getText().equals("Account ID")) {
    		txtAccID.setText("");
    	}
    }  
    
    private void txtAccIDFocusLost(java.awt.event.FocusEvent evt) {                                
    	if (txtAccID.getText().trim().equals("") || txtAccID.getText().trim().toLowerCase().equals("Account ID")) {
    		txtAccID.setText("Account ID");
    	}
    }

    private void passfPINFocusGained(java.awt.event.FocusEvent evt) {                                
    	if(String.valueOf(passfPin.getPassword()).equals("1234")) {
    		passfPin.setText("");
    	}
    }
    
    private void passfPinFocusLost(java.awt.event.FocusEvent evt) {                                
    	if (String.valueOf(passfPin.getPassword()).equals("") || String.valueOf(passfPin.getPassword()).equals("1234")) {
    		passfPin.setText("1234");
    	}
     }

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {                                     
        System.exit(0);
    }                                                                                                   
                               
//First Name
    private void FirstNActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
    }                                      
//Last Name
    private void LastNActionPerformed(java.awt.event.ActionEvent evt) {                                      
        // TODO add your handling code here:
    }                                     
//Pin
    private void PINActionPerformed(java.awt.event.ActionEvent evt) {                                    
        // TODO add your handling code here:
    }                                   
//Account Id
    private void AccIDActionPerformed(java.awt.event.ActionEvent evt) {                                      
        // TODO add your handling code here:
    }                                     
//age
    private void AgeActionPerformed(java.awt.event.ActionEvent evt) {                                    
        // TODO add your handling code here:
    }                                   

    private void jButton1MouseExited(java.awt.event.MouseEvent evt) {                                     
      btnSubmit.setBackground(new Color(255,255,255));
      btnSubmit.setForeground(new Color(0,0,0));
    }                                                                     

    private void jButton1MouseEntered(java.awt.event.MouseEvent evt) {                                      
      btnSubmit.setBackground(new Color(0,0,0));
      btnSubmit.setForeground(new Color(255,255,255));
    }                                     

    private void jButton2MouseEntered(java.awt.event.MouseEvent evt) {                                      
       btnGoToLogin.setForeground(new Color(45, 35, 158));
    }                                     

    private void jButton2MouseExited(java.awt.event.MouseEvent evt) {                                     
        btnGoToLogin.setForeground(new Color(0,0,0));
    }                                                                

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JTextField txtAccID;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFName;
    private javax.swing.JTextField txtLName;
    private javax.swing.JPasswordField passfPin;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JButton btnGoToLogin;
    private javax.swing.JLabel lblSignUp;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblMyBank;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    // End of variables declaration                   
}