/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package admindashboard;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import trackingandpayment.FpsDBConnection;
import java.text.SimpleDateFormat;
import java.awt.Color;
import java.awt.Toolkit;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class AdmAddFees extends JFrame {

    /**
     * Creates new form AddFees
     */
    public AdmAddFees() {
        initComponents();
        setTitle("Cash-VSU");
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/icons/MainIcon.png")));
    }
    
    private String adminPass;
    public AdmAddFees(String adminPass) {
        this.adminPass = adminPass;
        initComponents();        
        setTitle("Cash-VSU");
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/icons/MainIcon.png")));
    }
    
    private String date;
    private void getDate(){
        try{
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            date = sdf.format(dateChooser.getDate());
        }
        catch(Exception e) {
            date = null;
        }
    }
    
    private boolean verifyFields(){      
        return !(txtStudentNum.getText().isEmpty() || txtFeeCode.getText().isEmpty() || txtCategory.getText().isEmpty() || txtAmount.getText().isEmpty() || date == null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelsideBar = new javax.swing.JPanel();
        panelHome = new javax.swing.JPanel();
        btn_Home = new javax.swing.JLabel();
        panelSearchRec = new javax.swing.JPanel();
        lblPendingReq = new javax.swing.JLabel();
        panelEditCourses = new javax.swing.JPanel();
        lblStudRec = new javax.swing.JLabel();
        panelCoursesList = new javax.swing.JPanel();
        lblCTrans = new javax.swing.JLabel();
        panelViewAllRecord = new javax.swing.JPanel();
        lblTransHistory = new javax.swing.JLabel();
        panelBack = new javax.swing.JPanel();
        btn_Back = new javax.swing.JLabel();
        panelLogout = new javax.swing.JPanel();
        btn_Logout = new javax.swing.JLabel();
        cvsu_logo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        panelParent = new javax.swing.JPanel();
        txtFeeCode = new javax.swing.JTextField();
        lblAddFees = new javax.swing.JLabel();
        lblFeeCode = new javax.swing.JLabel();
        txtStudentNum = new javax.swing.JTextField();
        lblStudentNum = new javax.swing.JLabel();
        txtCategory = new javax.swing.JTextField();
        lblCategory = new javax.swing.JLabel();
        txtAmount = new javax.swing.JTextField();
        lblAmount = new javax.swing.JLabel();
        lblDueDate = new javax.swing.JLabel();
        dateChooser = new com.toedter.calendar.JDateChooser();
        btn_ConfirmTH = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelsideBar.setBackground(new java.awt.Color(0, 102, 102));
        panelsideBar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelHome.setBackground(new java.awt.Color(0, 102, 102));
        panelHome.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));

        btn_Home.setFont(new java.awt.Font("Sylfaen", 0, 20)); // NOI18N
        btn_Home.setForeground(new java.awt.Color(255, 255, 255));
        btn_Home.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        btn_Home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/home_1.png"))); // NOI18N
        btn_Home.setText("  HOME                      ");
        btn_Home.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_Home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_HomeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_HomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_HomeMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelHomeLayout = new javax.swing.GroupLayout(panelHome);
        panelHome.setLayout(panelHomeLayout);
        panelHomeLayout.setHorizontalGroup(
            panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelHomeLayout.createSequentialGroup()
                .addComponent(btn_Home, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelHomeLayout.setVerticalGroup(
            panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelHomeLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btn_Home))
        );

        panelsideBar.add(panelHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 270, 70));

        panelSearchRec.setBackground(new java.awt.Color(0, 102, 102));
        panelSearchRec.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));

        lblPendingReq.setFont(new java.awt.Font("Sylfaen", 0, 20)); // NOI18N
        lblPendingReq.setForeground(new java.awt.Color(255, 255, 255));
        lblPendingReq.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblPendingReq.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/search2.png"))); // NOI18N
        lblPendingReq.setText("Pending Requests       ");
        lblPendingReq.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblPendingReq.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblPendingReqMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblPendingReqMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblPendingReqMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelSearchRecLayout = new javax.swing.GroupLayout(panelSearchRec);
        panelSearchRec.setLayout(panelSearchRecLayout);
        panelSearchRecLayout.setHorizontalGroup(
            panelSearchRecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblPendingReq, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelSearchRecLayout.setVerticalGroup(
            panelSearchRecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSearchRecLayout.createSequentialGroup()
                .addGap(0, 2, Short.MAX_VALUE)
                .addComponent(lblPendingReq))
        );

        panelsideBar.add(panelSearchRec, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 270, 70));

        panelEditCourses.setBackground(new java.awt.Color(0, 102, 102));
        panelEditCourses.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));

        lblStudRec.setFont(new java.awt.Font("Sylfaen", 0, 20)); // NOI18N
        lblStudRec.setForeground(new java.awt.Color(255, 255, 255));
        lblStudRec.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblStudRec.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/edit2.png"))); // NOI18N
        lblStudRec.setText("Student Record           ");
        lblStudRec.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblStudRec.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblStudRecMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblStudRecMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblStudRecMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelEditCoursesLayout = new javax.swing.GroupLayout(panelEditCourses);
        panelEditCourses.setLayout(panelEditCoursesLayout);
        panelEditCoursesLayout.setHorizontalGroup(
            panelEditCoursesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblStudRec, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)
        );
        panelEditCoursesLayout.setVerticalGroup(
            panelEditCoursesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEditCoursesLayout.createSequentialGroup()
                .addComponent(lblStudRec)
                .addGap(0, 2, Short.MAX_VALUE))
        );

        panelsideBar.add(panelEditCourses, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 270, 70));

        panelCoursesList.setBackground(new java.awt.Color(0, 102, 102));
        panelCoursesList.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));

        lblCTrans.setFont(new java.awt.Font("Sylfaen", 0, 20)); // NOI18N
        lblCTrans.setForeground(new java.awt.Color(255, 255, 255));
        lblCTrans.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblCTrans.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/list_1.png"))); // NOI18N
        lblCTrans.setText("Confirm Transaction");
        lblCTrans.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblCTrans.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCTransMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblCTransMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblCTransMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelCoursesListLayout = new javax.swing.GroupLayout(panelCoursesList);
        panelCoursesList.setLayout(panelCoursesListLayout);
        panelCoursesListLayout.setHorizontalGroup(
            panelCoursesListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCoursesListLayout.createSequentialGroup()
                .addComponent(lblCTrans, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelCoursesListLayout.setVerticalGroup(
            panelCoursesListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCoursesListLayout.createSequentialGroup()
                .addComponent(lblCTrans)
                .addGap(0, 2, Short.MAX_VALUE))
        );

        panelsideBar.add(panelCoursesList, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, 270, 70));

        panelViewAllRecord.setBackground(new java.awt.Color(0, 102, 102));
        panelViewAllRecord.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));

        lblTransHistory.setFont(new java.awt.Font("Sylfaen", 0, 20)); // NOI18N
        lblTransHistory.setForeground(new java.awt.Color(255, 255, 255));
        lblTransHistory.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblTransHistory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/view all record.png"))); // NOI18N
        lblTransHistory.setText("Transaction History    ");
        lblTransHistory.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblTransHistory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblTransHistoryMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblTransHistoryMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblTransHistoryMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelViewAllRecordLayout = new javax.swing.GroupLayout(panelViewAllRecord);
        panelViewAllRecord.setLayout(panelViewAllRecordLayout);
        panelViewAllRecordLayout.setHorizontalGroup(
            panelViewAllRecordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTransHistory, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)
        );
        panelViewAllRecordLayout.setVerticalGroup(
            panelViewAllRecordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelViewAllRecordLayout.createSequentialGroup()
                .addComponent(lblTransHistory)
                .addGap(0, 2, Short.MAX_VALUE))
        );

        panelsideBar.add(panelViewAllRecord, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 460, 270, 70));

        panelBack.setBackground(new java.awt.Color(0, 102, 102));
        panelBack.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));

        btn_Back.setFont(new java.awt.Font("Sylfaen", 0, 20)); // NOI18N
        btn_Back.setForeground(new java.awt.Color(255, 255, 255));
        btn_Back.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        btn_Back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/left-arrow.png"))); // NOI18N
        btn_Back.setText(" Back                              ");
        btn_Back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_Back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_BackMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_BackMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_BackMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelBackLayout = new javax.swing.GroupLayout(panelBack);
        panelBack.setLayout(panelBackLayout);
        panelBackLayout.setHorizontalGroup(
            panelBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn_Back, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelBackLayout.setVerticalGroup(
            panelBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBackLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btn_Back))
        );

        panelsideBar.add(panelBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 550, 270, 70));

        panelLogout.setBackground(new java.awt.Color(0, 102, 102));
        panelLogout.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));

        btn_Logout.setFont(new java.awt.Font("Sylfaen", 0, 20)); // NOI18N
        btn_Logout.setForeground(new java.awt.Color(255, 255, 255));
        btn_Logout.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        btn_Logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/edit2.png"))); // NOI18N
        btn_Logout.setText("Logout                          ");
        btn_Logout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_Logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_LogoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_LogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_LogoutMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelLogoutLayout = new javax.swing.GroupLayout(panelLogout);
        panelLogout.setLayout(panelLogoutLayout);
        panelLogoutLayout.setHorizontalGroup(
            panelLogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn_Logout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelLogoutLayout.setVerticalGroup(
            panelLogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLogoutLayout.createSequentialGroup()
                .addComponent(btn_Logout)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        panelsideBar.add(panelLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 640, 270, -1));

        cvsu_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/24.png"))); // NOI18N
        panelsideBar.add(cvsu_logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 80, 80));

        jLabel2.setFont(new java.awt.Font("Timeline", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 153));
        jLabel2.setText("Cash-VSU");
        panelsideBar.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, -1, -1));

        getContentPane().add(panelsideBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 330, 850));

        panelParent.setBackground(new java.awt.Color(0, 153, 153));
        panelParent.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtFeeCode.setFont(new java.awt.Font("Source Code Pro", 0, 14)); // NOI18N
        txtFeeCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFeeCodeActionPerformed(evt);
            }
        });
        panelParent.add(txtFeeCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 320, 190, 40));

        lblAddFees.setFont(new java.awt.Font("Timeline", 0, 48)); // NOI18N
        lblAddFees.setForeground(new java.awt.Color(255, 255, 153));
        lblAddFees.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAddFees.setText("Add Fees");
        panelParent.add(lblAddFees, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 470, 80));

        lblFeeCode.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        lblFeeCode.setForeground(new java.awt.Color(255, 255, 153));
        lblFeeCode.setText("Fee Code");
        panelParent.add(lblFeeCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 290, 190, 30));

        txtStudentNum.setFont(new java.awt.Font("Source Code Pro", 0, 14)); // NOI18N
        txtStudentNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStudentNumActionPerformed(evt);
            }
        });
        panelParent.add(txtStudentNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, 190, 40));

        lblStudentNum.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        lblStudentNum.setForeground(new java.awt.Color(255, 255, 153));
        lblStudentNum.setText("Student Number");
        panelParent.add(lblStudentNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 190, 30));

        txtCategory.setFont(new java.awt.Font("Source Code Pro", 0, 14)); // NOI18N
        txtCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCategoryActionPerformed(evt);
            }
        });
        panelParent.add(txtCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 410, 190, 40));

        lblCategory.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        lblCategory.setForeground(new java.awt.Color(255, 255, 153));
        lblCategory.setText("Category");
        panelParent.add(lblCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 380, 190, 30));

        txtAmount.setFont(new java.awt.Font("Source Code Pro", 0, 14)); // NOI18N
        txtAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAmountActionPerformed(evt);
            }
        });
        txtAmount.addKeyListener(new KeyAdapter() {
            @Override
            public void keyTyped(KeyEvent e) {
                char c = e.getKeyChar();

                if(!Character.isDigit(c)) {
                    e.consume();
                }
            }
        });
        panelParent.add(txtAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 230, 190, 40));

        lblAmount.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        lblAmount.setForeground(new java.awt.Color(255, 255, 153));
        lblAmount.setText("Amount");
        panelParent.add(lblAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 200, 190, 30));

        lblDueDate.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        lblDueDate.setForeground(new java.awt.Color(255, 255, 153));
        lblDueDate.setText("Due Date");
        panelParent.add(lblDueDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 290, 190, 30));

        dateChooser.setToolTipText("");
        panelParent.add(dateChooser, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 320, 190, 40));

        btn_ConfirmTH.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        btn_ConfirmTH.setText("Confirm");
        btn_ConfirmTH.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_ConfirmTH.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        btn_ConfirmTH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ConfirmTHActionPerformed(evt);
            }
        });
        panelParent.add(btn_ConfirmTH, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 520, 160, 40));

        getContentPane().add(panelParent, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 0, 750, 850));

        setSize(new java.awt.Dimension(1095, 873));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_HomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_HomeMouseEntered
        Color clr = new Color (0,153,153);
        panelHome.setBackground(clr);
    }//GEN-LAST:event_btn_HomeMouseEntered

    private void btn_HomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_HomeMouseExited
        Color clr = new Color (0,103,103);
        panelHome.setBackground(clr);
    }//GEN-LAST:event_btn_HomeMouseExited

    private void lblPendingReqMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPendingReqMouseEntered
        Color clr = new Color (0,153,153);
        panelSearchRec.setBackground(clr);
    }//GEN-LAST:event_lblPendingReqMouseEntered

    private void lblPendingReqMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPendingReqMouseExited
        Color clr = new Color (0,103,103);
        panelSearchRec.setBackground(clr);
    }//GEN-LAST:event_lblPendingReqMouseExited

    private void lblStudRecMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblStudRecMouseEntered
        Color clr = new Color (0,153,153);
        panelEditCourses.setBackground(clr);
    }//GEN-LAST:event_lblStudRecMouseEntered

    private void lblStudRecMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblStudRecMouseExited
        Color clr = new Color (0,103,103);
        panelEditCourses.setBackground(clr);
    }//GEN-LAST:event_lblStudRecMouseExited

    private void lblCTransMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCTransMouseEntered
        Color clr = new Color (0,153,153);
        panelCoursesList.setBackground(clr);
    }//GEN-LAST:event_lblCTransMouseEntered

    private void lblCTransMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCTransMouseExited
        Color clr = new Color (0,103,103);
        panelCoursesList.setBackground(clr);
    }//GEN-LAST:event_lblCTransMouseExited

    private void lblTransHistoryMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTransHistoryMouseEntered
        Color clr = new Color (0,153,153);
        panelViewAllRecord.setBackground(clr);
    }//GEN-LAST:event_lblTransHistoryMouseEntered

    private void lblTransHistoryMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTransHistoryMouseExited
        Color clr = new Color (0,103,103);
        panelViewAllRecord.setBackground(clr);
    }//GEN-LAST:event_lblTransHistoryMouseExited

    private void btn_BackMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_BackMouseEntered
        Color clr = new Color (0,153,153);
        panelBack.setBackground(clr);
    }//GEN-LAST:event_btn_BackMouseEntered

    private void btn_BackMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_BackMouseExited
        Color clr = new Color (0,103,103);
        panelBack.setBackground(clr);
    }//GEN-LAST:event_btn_BackMouseExited

    private void btn_LogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_LogoutMouseEntered
        Color clr = new Color (0,153,153);
        panelLogout.setBackground(clr);
    }//GEN-LAST:event_btn_LogoutMouseEntered

    private void btn_LogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_LogoutMouseExited
        Color clr = new Color (0,103,103);
        panelLogout.setBackground(clr);
    }//GEN-LAST:event_btn_LogoutMouseExited

    private void btn_HomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_HomeMouseClicked
        AdmHome home = new AdmHome(adminPass);
        home.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_HomeMouseClicked

    private void btn_LogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_LogoutMouseClicked
        AdmLogin lgn = new AdmLogin();
        lgn.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_LogoutMouseClicked

    private void btn_BackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_BackMouseClicked
        AdmHome home = new AdmHome(adminPass);
        home.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_BackMouseClicked

    private void lblStudRecMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblStudRecMouseClicked
        AdmStudRecord stdntrcd = new AdmStudRecord(adminPass);
        stdntrcd.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblStudRecMouseClicked

    private void lblPendingReqMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPendingReqMouseClicked
        AdmPendingReq pr = new AdmPendingReq(adminPass);
        pr.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblPendingReqMouseClicked

    private void lblCTransMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCTransMouseClicked
        AdmConfirmTrans curslst = new AdmConfirmTrans(adminPass);
        curslst.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_lblCTransMouseClicked

    private void lblTransHistoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTransHistoryMouseClicked
        AdmTranHistory th = new AdmTranHistory(adminPass);
        th.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblTransHistoryMouseClicked

    private void txtFeeCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFeeCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFeeCodeActionPerformed

    private void txtStudentNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStudentNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStudentNumActionPerformed

    private void txtCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCategoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCategoryActionPerformed

    private void txtAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAmountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAmountActionPerformed

    private void btn_ConfirmTHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ConfirmTHActionPerformed
        Connection conn = null;   
        getDate();
        if (verifyFields() == false){
            JOptionPane.showMessageDialog(this, "Missing Information!");
        }
        else{           
           try{
                // connect to database
                conn = FpsDBConnection.dbConnect();

                // looks if student number exists
                String query = "SELECT * FROM tbl_user WHERE StudentNum = ?";
                PreparedStatement ps = conn.prepareStatement(query);
                ps.setString(1, txtStudentNum.getText());
                ResultSet rs = ps.executeQuery();

                // student number exists
                if(rs.next()){
                    // adding of data when Amount is valid
                    if(Integer.parseInt(txtAmount.getText()) != 0){
                        String query2 = "INSERT INTO tbl_fee_list (FeeCode, StudentNum, Category, Amount, DueDate) VALUES (?,?,?,?,?)";
                        PreparedStatement ps2 = conn.prepareStatement(query2);
                        ps2.setString(1, txtFeeCode.getText());
                        ps2.setString(2, txtStudentNum.getText());
                        ps2.setString(3, txtCategory.getText());
                        ps2.setInt(4, Integer.parseInt(txtAmount.getText()));
                        ps2.setString(5, date);

                        ps2.executeUpdate();
                        JOptionPane.showMessageDialog(this, "Fee is successfully added.");
                        txtFeeCode.setText("");
                        txtStudentNum.setText("");
                        txtCategory.setText("");
                        txtAmount.setText("");                    
                    }             
                    else{
                        JOptionPane.showMessageDialog(this, "Amount cannot be zero.");
                        txtAmount.setText("");
                    }
                }
                else{
                    JOptionPane.showMessageDialog(this, "Student Number does not exist.");
                    txtStudentNum.setText("");
                }           
            }
            catch(SQLException ex){
                JOptionPane.showMessageDialog(this, ex);
            } 
        }
                
    }//GEN-LAST:event_btn_ConfirmTHActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdmAddFees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdmAddFees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdmAddFees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdmAddFees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdmAddFees().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btn_Back;
    private javax.swing.JButton btn_ConfirmTH;
    private javax.swing.JLabel btn_Home;
    private javax.swing.JLabel btn_Logout;
    private javax.swing.JLabel cvsu_logo;
    private com.toedter.calendar.JDateChooser dateChooser;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblAddFees;
    private javax.swing.JLabel lblAmount;
    private javax.swing.JLabel lblCTrans;
    private javax.swing.JLabel lblCategory;
    private javax.swing.JLabel lblDueDate;
    private javax.swing.JLabel lblFeeCode;
    private javax.swing.JLabel lblPendingReq;
    private javax.swing.JLabel lblStudRec;
    private javax.swing.JLabel lblStudentNum;
    private javax.swing.JLabel lblTransHistory;
    private javax.swing.JPanel panelBack;
    private javax.swing.JPanel panelCoursesList;
    private javax.swing.JPanel panelEditCourses;
    private javax.swing.JPanel panelHome;
    private javax.swing.JPanel panelLogout;
    private javax.swing.JPanel panelParent;
    private javax.swing.JPanel panelSearchRec;
    private javax.swing.JPanel panelViewAllRecord;
    private javax.swing.JPanel panelsideBar;
    private javax.swing.JTextField txtAmount;
    private javax.swing.JTextField txtCategory;
    private javax.swing.JTextField txtFeeCode;
    private javax.swing.JTextField txtStudentNum;
    // End of variables declaration//GEN-END:variables
}
