/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package admindashboard;

import java.awt.Color;
import java.awt.Toolkit;
import javax.swing.JFrame;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
import trackingandpayment.FpsDBConnection;
/**
 *
 * @author User
 */
public class AdmPendingReq extends JFrame {

    /**
     * Creates new form AddFees
     */
    public AdmPendingReq() {
        initComponents();
        grabData();      
        setTitle("Cash-VSU");
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/icons/MainIcon.png")));
    }
    
    private String adminPass;
    public AdmPendingReq(String adminPass) {
        this.adminPass = adminPass;
        initComponents();       
        grabData();      
        setTitle("Cash-VSU");
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/icons/MainIcon.png")));
    }
    
    private void grabData() {
        Connection conn = null;
        try{
            conn = FpsDBConnection.dbConnect();
            String query = "SELECT f.FeeCode AS 'Fee Code', f.StudentNum AS 'Student No.', f.Category, f.Amount, f.DueDate AS 'Due Date', p.DateRequested AS 'Date Requested' FROM tbl_pending p INNER JOIN tbl_fee_list f ON p.FeeCode = f.FeeCode";
            PreparedStatement ps = conn.prepareStatement(query);
            ResultSet rs = ps.executeQuery();
            tblPending.setModel(DbUtils.resultSetToTableModel(rs));
        }
        catch(SQLException ex){
            ex.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelsideBar = new javax.swing.JPanel();
        panelBack = new javax.swing.JPanel();
        btn_Back = new javax.swing.JLabel();
        panelLogout = new javax.swing.JPanel();
        btn_Logout = new javax.swing.JLabel();
        cvsu_logo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        panelHome = new javax.swing.JPanel();
        btn_Home = new javax.swing.JLabel();
        panelSearchRec = new javax.swing.JPanel();
        lblPendingReq = new javax.swing.JLabel();
        panelEditCourses = new javax.swing.JPanel();
        btn_StudentRecord = new javax.swing.JLabel();
        panelCoursesList = new javax.swing.JPanel();
        btn_ConfirmTransaction = new javax.swing.JLabel();
        panelViewAllRecord = new javax.swing.JPanel();
        TransactionHistory = new javax.swing.JLabel();
        panelParent = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPending = new javax.swing.JTable();
        lblPending = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelsideBar.setBackground(new java.awt.Color(0, 102, 102));
        panelsideBar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelBack.setBackground(new java.awt.Color(0, 102, 102));
        panelBack.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));

        btn_Back.setFont(new java.awt.Font("Sylfaen", 0, 20)); // NOI18N
        btn_Back.setForeground(new java.awt.Color(255, 255, 255));
        btn_Back.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        btn_Back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/left-arrow.png"))); // NOI18N
        btn_Back.setText(" Back                              ");
        btn_Back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_Back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_BackMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_BackMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_BackMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelBackLayout = new javax.swing.GroupLayout(panelBack);
        panelBack.setLayout(panelBackLayout);
        panelBackLayout.setHorizontalGroup(
            panelBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn_Back, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)
        );
        panelBackLayout.setVerticalGroup(
            panelBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBackLayout.createSequentialGroup()
                .addGap(0, 2, Short.MAX_VALUE)
                .addComponent(btn_Back))
        );

        panelsideBar.add(panelBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 550, 270, 70));

        panelLogout.setBackground(new java.awt.Color(0, 102, 102));
        panelLogout.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));

        btn_Logout.setFont(new java.awt.Font("Sylfaen", 0, 20)); // NOI18N
        btn_Logout.setForeground(new java.awt.Color(255, 255, 255));
        btn_Logout.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        btn_Logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/edit2.png"))); // NOI18N
        btn_Logout.setText("Logout                          ");
        btn_Logout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_Logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_LogoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_LogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_LogoutMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelLogoutLayout = new javax.swing.GroupLayout(panelLogout);
        panelLogout.setLayout(panelLogoutLayout);
        panelLogoutLayout.setHorizontalGroup(
            panelLogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn_Logout, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)
        );
        panelLogoutLayout.setVerticalGroup(
            panelLogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLogoutLayout.createSequentialGroup()
                .addComponent(btn_Logout)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        panelsideBar.add(panelLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 640, 270, -1));

        cvsu_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/24.png"))); // NOI18N
        panelsideBar.add(cvsu_logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 80, 80));

        jLabel2.setFont(new java.awt.Font("Timeline", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 153));
        jLabel2.setText("Cash-VSU");
        panelsideBar.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, -1, -1));

        panelHome.setBackground(new java.awt.Color(0, 102, 102));
        panelHome.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));

        btn_Home.setFont(new java.awt.Font("Sylfaen", 0, 20)); // NOI18N
        btn_Home.setForeground(new java.awt.Color(255, 255, 255));
        btn_Home.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        btn_Home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/home_1.png"))); // NOI18N
        btn_Home.setText("  HOME                      ");
        btn_Home.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_Home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_HomeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_HomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_HomeMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelHomeLayout = new javax.swing.GroupLayout(panelHome);
        panelHome.setLayout(panelHomeLayout);
        panelHomeLayout.setHorizontalGroup(
            panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn_Home, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)
        );
        panelHomeLayout.setVerticalGroup(
            panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelHomeLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btn_Home))
        );

        panelsideBar.add(panelHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 270, 70));

        panelSearchRec.setBackground(new java.awt.Color(0, 102, 102));
        panelSearchRec.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));

        lblPendingReq.setFont(new java.awt.Font("Sylfaen", 0, 20)); // NOI18N
        lblPendingReq.setForeground(new java.awt.Color(255, 255, 255));
        lblPendingReq.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblPendingReq.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/search2.png"))); // NOI18N
        lblPendingReq.setText("Pending Requests       ");
        lblPendingReq.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblPendingReq.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblPendingReqMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblPendingReqMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblPendingReqMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelSearchRecLayout = new javax.swing.GroupLayout(panelSearchRec);
        panelSearchRec.setLayout(panelSearchRecLayout);
        panelSearchRecLayout.setHorizontalGroup(
            panelSearchRecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblPendingReq, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)
        );
        panelSearchRecLayout.setVerticalGroup(
            panelSearchRecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSearchRecLayout.createSequentialGroup()
                .addGap(0, 2, Short.MAX_VALUE)
                .addComponent(lblPendingReq))
        );

        panelsideBar.add(panelSearchRec, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 270, 70));

        panelEditCourses.setBackground(new java.awt.Color(0, 102, 102));
        panelEditCourses.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));

        btn_StudentRecord.setFont(new java.awt.Font("Sylfaen", 0, 20)); // NOI18N
        btn_StudentRecord.setForeground(new java.awt.Color(255, 255, 255));
        btn_StudentRecord.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        btn_StudentRecord.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/edit2.png"))); // NOI18N
        btn_StudentRecord.setText("Student Record           ");
        btn_StudentRecord.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_StudentRecord.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_StudentRecordMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_StudentRecordMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_StudentRecordMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelEditCoursesLayout = new javax.swing.GroupLayout(panelEditCourses);
        panelEditCourses.setLayout(panelEditCoursesLayout);
        panelEditCoursesLayout.setHorizontalGroup(
            panelEditCoursesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn_StudentRecord, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)
        );
        panelEditCoursesLayout.setVerticalGroup(
            panelEditCoursesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEditCoursesLayout.createSequentialGroup()
                .addComponent(btn_StudentRecord)
                .addGap(0, 2, Short.MAX_VALUE))
        );

        panelsideBar.add(panelEditCourses, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 270, 70));

        panelCoursesList.setBackground(new java.awt.Color(0, 102, 102));
        panelCoursesList.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));

        btn_ConfirmTransaction.setFont(new java.awt.Font("Sylfaen", 0, 20)); // NOI18N
        btn_ConfirmTransaction.setForeground(new java.awt.Color(255, 255, 255));
        btn_ConfirmTransaction.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        btn_ConfirmTransaction.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/list_1.png"))); // NOI18N
        btn_ConfirmTransaction.setText("Confirm Transaction");
        btn_ConfirmTransaction.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_ConfirmTransaction.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_ConfirmTransactionMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_ConfirmTransactionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_ConfirmTransactionMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelCoursesListLayout = new javax.swing.GroupLayout(panelCoursesList);
        panelCoursesList.setLayout(panelCoursesListLayout);
        panelCoursesListLayout.setHorizontalGroup(
            panelCoursesListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCoursesListLayout.createSequentialGroup()
                .addComponent(btn_ConfirmTransaction, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelCoursesListLayout.setVerticalGroup(
            panelCoursesListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCoursesListLayout.createSequentialGroup()
                .addComponent(btn_ConfirmTransaction)
                .addGap(0, 2, Short.MAX_VALUE))
        );

        panelsideBar.add(panelCoursesList, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, 270, 70));

        panelViewAllRecord.setBackground(new java.awt.Color(0, 102, 102));
        panelViewAllRecord.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));

        TransactionHistory.setFont(new java.awt.Font("Sylfaen", 0, 20)); // NOI18N
        TransactionHistory.setForeground(new java.awt.Color(255, 255, 255));
        TransactionHistory.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        TransactionHistory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/view all record.png"))); // NOI18N
        TransactionHistory.setText("Transaction History    ");
        TransactionHistory.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TransactionHistory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TransactionHistoryMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                TransactionHistoryMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                TransactionHistoryMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelViewAllRecordLayout = new javax.swing.GroupLayout(panelViewAllRecord);
        panelViewAllRecord.setLayout(panelViewAllRecordLayout);
        panelViewAllRecordLayout.setHorizontalGroup(
            panelViewAllRecordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TransactionHistory, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)
        );
        panelViewAllRecordLayout.setVerticalGroup(
            panelViewAllRecordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelViewAllRecordLayout.createSequentialGroup()
                .addComponent(TransactionHistory)
                .addGap(0, 2, Short.MAX_VALUE))
        );

        panelsideBar.add(panelViewAllRecord, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 460, 270, 70));

        getContentPane().add(panelsideBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 330, 850));

        panelParent.setBackground(new java.awt.Color(0, 153, 153));
        panelParent.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblPending.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblPending);

        panelParent.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 680, 470));

        lblPending.setFont(new java.awt.Font("Timeline", 0, 48)); // NOI18N
        lblPending.setForeground(new java.awt.Color(255, 255, 153));
        lblPending.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPending.setText("Pending Requests");
        panelParent.add(lblPending, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 420, 80));

        getContentPane().add(panelParent, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 0, 750, 850));

        setSize(new java.awt.Dimension(1095, 873));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_BackMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_BackMouseEntered
        Color clr = new Color (0,153,153);
        panelBack.setBackground(clr);
    }//GEN-LAST:event_btn_BackMouseEntered

    private void btn_BackMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_BackMouseExited
        Color clr = new Color (0,103,103);
        panelBack.setBackground(clr);
    }//GEN-LAST:event_btn_BackMouseExited

    private void btn_LogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_LogoutMouseEntered
        Color clr = new Color (0,153,153);
        panelLogout.setBackground(clr);
    }//GEN-LAST:event_btn_LogoutMouseEntered

    private void btn_LogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_LogoutMouseExited
        Color clr = new Color (0,103,103);
        panelLogout.setBackground(clr);
    }//GEN-LAST:event_btn_LogoutMouseExited

    private void btn_LogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_LogoutMouseClicked
        AdmLogin lgn = new AdmLogin();
        lgn.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_LogoutMouseClicked

    private void btn_BackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_BackMouseClicked
        AdmHome home = new AdmHome(adminPass);
        home.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_BackMouseClicked

    private void btn_HomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_HomeMouseClicked
        AdmHome home = new AdmHome(adminPass);
        home.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_HomeMouseClicked

    private void btn_HomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_HomeMouseEntered
        Color clr = new Color (0,153,153);
        panelHome.setBackground(clr);
    }//GEN-LAST:event_btn_HomeMouseEntered

    private void btn_HomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_HomeMouseExited
        Color clr = new Color (0,103,103);
        panelHome.setBackground(clr);
    }//GEN-LAST:event_btn_HomeMouseExited

    private void lblPendingReqMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPendingReqMouseClicked
        AdmPendingReq Srchrcrd = new AdmPendingReq(adminPass);
        Srchrcrd.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblPendingReqMouseClicked

    private void lblPendingReqMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPendingReqMouseEntered
        Color clr = new Color (0,153,153);
        panelSearchRec.setBackground(clr);
    }//GEN-LAST:event_lblPendingReqMouseEntered

    private void lblPendingReqMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPendingReqMouseExited
        Color clr = new Color (0,103,103);
        panelSearchRec.setBackground(clr);
    }//GEN-LAST:event_lblPendingReqMouseExited

    private void btn_StudentRecordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_StudentRecordMouseClicked
        AdmStudRecord stdntrcd = new AdmStudRecord(adminPass);
        stdntrcd.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_StudentRecordMouseClicked

    private void btn_StudentRecordMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_StudentRecordMouseEntered
        Color clr = new Color (0,153,153);
        panelEditCourses.setBackground(clr);
    }//GEN-LAST:event_btn_StudentRecordMouseEntered

    private void btn_StudentRecordMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_StudentRecordMouseExited
        Color clr = new Color (0,103,103);
        panelEditCourses.setBackground(clr);
    }//GEN-LAST:event_btn_StudentRecordMouseExited

    private void btn_ConfirmTransactionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ConfirmTransactionMouseClicked
        AdmConfirmTrans vwalrcd = new AdmConfirmTrans(adminPass);
        vwalrcd.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_ConfirmTransactionMouseClicked

    private void btn_ConfirmTransactionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ConfirmTransactionMouseEntered
        Color clr = new Color (0,153,153);
        panelCoursesList.setBackground(clr);
    }//GEN-LAST:event_btn_ConfirmTransactionMouseEntered

    private void btn_ConfirmTransactionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ConfirmTransactionMouseExited
        Color clr = new Color (0,103,103);
        panelCoursesList.setBackground(clr);
    }//GEN-LAST:event_btn_ConfirmTransactionMouseExited

    private void TransactionHistoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TransactionHistoryMouseClicked
        AdmTranHistory trnscthstry = new AdmTranHistory(adminPass);
        trnscthstry.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_TransactionHistoryMouseClicked

    private void TransactionHistoryMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TransactionHistoryMouseEntered
        Color clr = new Color (0,153,153);
        panelViewAllRecord.setBackground(clr);
    }//GEN-LAST:event_TransactionHistoryMouseEntered

    private void TransactionHistoryMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TransactionHistoryMouseExited
        Color clr = new Color (0,103,103);
        panelViewAllRecord.setBackground(clr);
    }//GEN-LAST:event_TransactionHistoryMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdmPendingReq.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdmPendingReq.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdmPendingReq.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdmPendingReq.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdmPendingReq().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel TransactionHistory;
    private javax.swing.JLabel btn_Back;
    private javax.swing.JLabel btn_ConfirmTransaction;
    private javax.swing.JLabel btn_Home;
    private javax.swing.JLabel btn_Logout;
    private javax.swing.JLabel btn_StudentRecord;
    private javax.swing.JLabel cvsu_logo;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblPending;
    private javax.swing.JLabel lblPendingReq;
    private javax.swing.JPanel panelBack;
    private javax.swing.JPanel panelCoursesList;
    private javax.swing.JPanel panelEditCourses;
    private javax.swing.JPanel panelHome;
    private javax.swing.JPanel panelLogout;
    private javax.swing.JPanel panelParent;
    private javax.swing.JPanel panelSearchRec;
    private javax.swing.JPanel panelViewAllRecord;
    private javax.swing.JPanel panelsideBar;
    private javax.swing.JTable tblPending;
    // End of variables declaration//GEN-END:variables
}
